version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    # add command for jetstream
    command: ["-js"]
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./tools/mosquitto-config/:/mosquitto/config/:ro
      - mosquitto-data:/mosquitto/log/
      - mosquitto-data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  influxdb:
      image: influxdb:2.0.7
      environment:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
          DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
          DOCKER_INFLUXDB_INIT_ORG: iot
          DOCKER_INFLUXDB_INIT_BUCKET: users_business_events
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      ports:
      - "8086:8086"
volumes:
  mongodb-data:
  redis-data:
  mosquitto-data: